# Generated by Django 4.0.4 on 2022-04-29 04:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Champion',
            fields=[
                ('key', models.IntegerField(primary_key=True, serialize=False)),
                ('id', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=100)),
                ('lore', models.TextField()),
                ('blurb', models.TextField()),
                ('allytips', models.TextField()),
                ('enemytips', models.TextField()),
                ('tags', models.CharField(max_length=100)),
                ('partype', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ChampionPassive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('champion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='model_champion.champion')),
            ],
        ),
        migrations.CreateModel(
            name='ChampionSpell',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=100)),
                ('tooltip', models.TextField()),
                ('maxrank', models.IntegerField()),
                ('cooldown', models.CharField(max_length=100)),
                ('cooldownBurn', models.CharField(max_length=100)),
                ('cost', models.CharField(max_length=100)),
                ('costBurn', models.CharField(max_length=100)),
                ('costType', models.CharField(max_length=100)),
                ('range', models.CharField(max_length=100)),
                ('resource', models.CharField(max_length=100)),
                ('champion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='model_champion.champion')),
            ],
        ),
        migrations.CreateModel(
            name='SpellImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full', models.CharField(max_length=100)),
                ('sprite', models.CharField(max_length=100)),
                ('group', models.CharField(max_length=100)),
                ('x', models.IntegerField()),
                ('y', models.IntegerField()),
                ('W', models.IntegerField()),
                ('h', models.IntegerField()),
                ('spell', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='model_champion.championspell')),
            ],
        ),
        migrations.CreateModel(
            name='PassiveImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full', models.CharField(max_length=100)),
                ('sprite', models.CharField(max_length=100)),
                ('group', models.CharField(max_length=100)),
                ('x', models.IntegerField()),
                ('y', models.IntegerField()),
                ('W', models.IntegerField()),
                ('h', models.IntegerField()),
                ('passive', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='model_champion.championpassive')),
            ],
        ),
        migrations.CreateModel(
            name='ChampionStat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hp', models.IntegerField()),
                ('hpperlevel', models.IntegerField()),
                ('mp', models.IntegerField()),
                ('mpperlevel', models.IntegerField()),
                ('movespeed', models.IntegerField()),
                ('armor', models.IntegerField()),
                ('armorperlevel', models.IntegerField()),
                ('spellblock', models.IntegerField()),
                ('spellblockperlevel', models.IntegerField()),
                ('attackrange', models.IntegerField()),
                ('hpregen', models.IntegerField()),
                ('hpregenperlevel', models.IntegerField()),
                ('mpregen', models.IntegerField()),
                ('mpregenperlevel', models.IntegerField()),
                ('crit', models.IntegerField()),
                ('critperlevel', models.IntegerField()),
                ('attackdamage', models.IntegerField()),
                ('attackdamageperlevel', models.IntegerField()),
                ('attackspeedperlevel', models.IntegerField()),
                ('attackspeed', models.IntegerField()),
                ('champion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='model_champion.champion')),
            ],
        ),
        migrations.CreateModel(
            name='ChampionSkin',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('num', models.IntegerField()),
                ('name', models.CharField(max_length=100)),
                ('chromas', models.BooleanField()),
                ('champion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='model_champion.champion')),
            ],
        ),
        migrations.CreateModel(
            name='ChampionInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attack', models.IntegerField()),
                ('defense', models.IntegerField()),
                ('magic', models.IntegerField()),
                ('difficulty', models.IntegerField()),
                ('champion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='model_champion.champion')),
            ],
        ),
        migrations.CreateModel(
            name='ChampionImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full', models.CharField(max_length=100)),
                ('sprite', models.CharField(max_length=100)),
                ('group', models.CharField(max_length=100)),
                ('x', models.IntegerField()),
                ('y', models.IntegerField()),
                ('W', models.IntegerField()),
                ('h', models.IntegerField()),
                ('champion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='model_champion.champion')),
            ],
        ),
    ]
